### ISSUE TITLE
Add pod and service labels

### ISSUE THREAD

**Issue by JimBugwadia** [nirmata/kube-netc#10]
add labels like:
- source_address
- destination_address,
- source_name
- destination_name,
- source_kind
- destination_kind
- source_namespace
- destination_namespace
- source_node
- destination_node

We may also want to include standard labels: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

See proposal at:

https://docs.google.com/document/d/1WL98CLbDcdFY65Sg2Dx0AQB3tguZfw7LZYJlZHr3vm4/edit?pli=1

**Comment by drewrip** [comment]
The new labels have been implemented in e4fbc02 as per the label proposal in the given doc.

The current labels for each metric are:
- name
- component
- instance
- version
- part_of
- managed_by
- source_address
- destination_address
- source_name
- destination_name
- source_kind
- destination_kind
- source_namespace
- destination_namespace
- source_node
- destination_node
