### ISSUE TITLE
kube-netc pod not showing when following getting started

### ISSUE THREAD

**Issue by RinkiyaKeDad** [nirmata/kube-netc#23]
Hi! I was trying out kube-netc by following the [Getting Started](https://github.com/nirmata/kube-netc#getting-started) guide. I tried using both `minikube` and `kind` clusters but did not see the kube-netc pod listed after installing the daemon set. 

I did receive a warning though after installing the daemon set which could be the reason for this. I've attached a screenshot of my terminal showing the exact commands I ran. Please let me know if I messed up something while setting up if that's the case. Thanks.

![kubenetc](https://user-images.githubusercontent.com/56963264/105502580-957d0300-5ceb-11eb-8009-8de41fa26075.png)

**Comment by drewrip** [comment]
I'm not at my computer right now but hopefully this can help. It looks like the Getting started guide might be slightly out of date with the get pods command. Could you try:

`kubectl get pods --all-namespaces`

I don't think the warning is affecting kube-netc just yet, but I'll go ahead and open an issue about this so we can get it updated.

**Comment by RinkiyaKeDad** [comment]
Thanks, @drewrip. I'll test that out when I'm on my computer and will raise a PR to fix the guide if that works.
