### ISSUE TITLE
fix CI builds

### ISSUE THREAD

**Issue by JimBugwadia** [nirmata/kube-netc#8]
Travis is showing a build error:

https://travis-ci.org/github/nirmata/kube-netc

**Comment by drewrip** [comment]
Travis failed a simple curl for an unknown reason. I wasn't able to reproduce the problem. And the successive builds have passed.

**Comment by JimBugwadia** [comment]
@drewrip - the Build Status badge in the README still shows `error`

**Comment by drewrip** [comment]
That's interesting, mine seems to show it passing.


![image](https://user-images.githubusercontent.com/22136823/84840369-57a95500-b00d-11ea-80ee-4f5d061fdc13.png)


I just submitted another passing commit, hopefully that fixed the badge on your end?

**Comment by JimBugwadia** [comment]
works now...!
