### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by JimBugwadia** [nirmata/kube-netc#9]
Some suggested changes:

1. Put a "Getting Started" section upfront with sub-sections for "Install kube-netc" and "View results".
2. Remove Examples
3. Move design sections into a separate doc

**Comment by drewrip** [comment]
The deprecated examples section has been removed and the demo has been broken down and renamed to "Getting Started". I also created a design doc and linked it at the bottom.

We can of course add more information later but at the moment I think we are in a good place for basic documentation for interested users.
